feat: финальное задание спринта 16
grand1964/java-shareit pull request #4
Opened 2023-09-08 14:43 UTC by grand1964

Add docker

2023-09-09 12:06 UTC, NikolaiDem requested changes

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Controller
Вместо использования Controller можно использовать RestController. Тогда ResponseEntity<Object> можно заменить на тип объекта, например, BookingDto
Аналогично для остальных контроллеров.

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        //.orElseThrow(() -> new BadRequestException("Неверный параметр запроса: " + stateParam));
Лишние комментарии.
Аналогично далее

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Validation.validateId(ownerId);
Вместо кастомной валидации можно использовать @Positive над аргументом эндпоинта.
Аналогично для остальных валидаций

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Validation.validateBookingDto(bookingInDto); //проверяем корректность границ
Используется только в этом контроллере, можно перенести validateBookingDto из Validation в этот метод

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +        for (BookingState state : values()) {
Можно проще:
        return Arrays.stream(values())
                .filter(state -> state.name().equalsIgnoreCase(stringState))
                .findFirst();

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/common/validation/Validation.java
> +public class Validation {
Этот класс лишний. Он объединяет методы, которые используются по одному разу в каждом из контроллеров.
Метафора: есть 3 человека, живущих в Москве, Париже и Лондоне. Все хотят знать только свое локальное время, но все часы находятся в Сиднее

2023-09-09 12:06 UTC, NikolaiDem commented on gateway/src/test/java/ru/practicum/shareit/mvc/RequestControllerMvcTest.java
> +        mvc.perform(get("/requests/{id}", -1)
Тестовый метод в идеале должен содержать проверку чего-то одного. Здесь будто бы логически 2 одинаковых теста.
Так как отличие только в id, то можно использовать параметризацию.
https://www.baeldung.com/parameterized-tests-junit-5
Аналогично для остальных тестовых классов и методов.

2023-09-09 12:06 UTC, NikolaiDem commented on server/pom.xml
> +		<dependency>
Валидация в server модуле не нужна

2023-09-09 12:06 UTC, NikolaiDem commented on server/src/main/java/ru/practicum/shareit/common/exception/ErrorResponse.java
> +@Getter
Вместо геттера и конструктора можно использовать @Value из lombok

2023-09-09 12:06 UTC, NikolaiDem commented on docker-compose.yml
> +      - DB_NAME=shareit
Следующие 3 параметра бесполезны, потому что их никто не использует)
В application.properties захардкожены параметры подключения к БД
spring.datasource.url=jdbc:postgresql://localhost:6541/shareit
spring.datasource.username=root
spring.datasource.password=root
Лучше сделать так, чтобы docker-compose устанавливал переменные среды для url, user и password подключения к БД. А application.properties использовал данные из этих переменных среды)

2023-09-09 17:41 UTC, grand1964 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Controller
Привет, Николай! Аннотации я заменил. Но в ResponseEntity приходят выходные dto-объекты, которых в gateway нет. Да им там и не место: gateway нужно лишь для валидации входных данных и не отвечает за выходные. Так зачем их туда включать?

2023-09-09 17:45 UTC, grand1964 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Validation.validateId(ownerId);
Кастомную валидацию айдишников придется оставить из-за проблем с постманом. У меня исключение ConstraintValidation привязано к ошибке 400, а постман при неверном айдишнике ожидает 404. Привязать ConstraintValidation к 404 тоже нельзя, тогда другие тесты упадут.
Поскольку класса Validation уже нет, я включил валидацию айдишников во все контроллеры.

2023-09-10 16:54 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Validation.validateId(ownerId);
Окей, в таком случае получаем, что диапазон айдишников никак не ограничен. Тогда и валидация здесь не нужна. И запрос мы сразу перенаправляем серверу, который уже может ответить 404, что объект по такому id не найден

2023-09-10 16:55 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Controller
Андрей, привет!
Согласен)

2023-09-10 16:56 UTC, NikolaiDem approved these changes

2023-09-11 05:55 UTC, merged